version: '3'

services:

  collector:
    container_name: collector
    build: ./collector
    environment:
      TZ: CET
      KAFKA_BROKER_URL: broker:9092
    volumes: 
      - ./logs:/logs:rw
    networks:
      - api
      - storage

  generator:
    container_name: generator
    build: ./generator
    environment:
      TZ: CET
      LINES_PER_SECOND: 0.5
      COLLECTOR_URL: collector
    volumes: 
      - ./logs:/logs:rw
    networks:
      - api
    depends_on:
      - collector

  classifier:
    container_name: classifier
    build: ./classifier
    environment:
      TZ: CET
      KAFKA_BROKER_URL: broker:9092
    volumes: 
      - ./logs:/logs:rw
    networks:
      - storage

  influxdb:
    container_name: influxdb
    build: ./influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE : setup
      DOCKER_INFLUXDB_INIT_USERNAME : admin
      DOCKER_INFLUXDB_INIT_PASSWORD : adminadmin
      DOCKER_INFLUXDB_INIT_ORG : fireman
      DOCKER_INFLUXDB_INIT_BUCKET: fireman
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN : S7UsPhCb6gwukLBDxp-p7DpuXzqdeM_xDCaJBAF8koH4vaqyO-0rXg6NhWYSc1LvIyIF2j4KftumFV76gwfzSQ==
      TZ: CET
    ports:
      - 8086:8086
    networks:
      - storage

  telegraf:
    container_name: telegraf
    build: ./telegraf
    environment:
      TZ: CET
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - storage
    depends_on:
      - influxdb

networks:
  storage:
    driver: bridge
  api:
    driver: bridge
