version: '3'

services:

  generator:
    build: ./generator
    environment:
      KAFKA_BROKER_URL: broker:9092
      DATA_TOPIC: streaming.data
      LINES_PER_SECOND: 0.5
    volumes: 
      - ./logs:/logs:rw

  classifier:
    build: ./classifier
    environment:
      KAFKA_BROKER_URL: broker:9092
      DATA_TOPIC: streaming.data
    volumes: 
      - ./logs:/logs:rw

  influxdb:
    container_name: influxdb
    image: influxdb:latest
    ports:
      - 8086:8086
          
  grafana:
    container_name: grafana
    build: ./grafana
    ports: 
      - 3000:3000

networks:
  default:
    external:
      name: kafka-network
