version: '3'

services:

  collector:
    container_name: collector
    build: ./collector
    environment:
      TZ: CET
      KAFKA_BROKER_URL: broker:9092
    volumes: 
      - ./logs:/logs:rw
    networks:
      - api
      - storage

  generator:
    container_name: generator
    build: ./generator
    environment:
      TZ: CET
      LINES_PER_SECOND: 0.5
      COLLECTOR_URL: collector
    volumes: 
      - ./logs:/logs:rw
    networks:
      - api
    depends_on:
      - collector

  classifier:
    container_name: classifier
    build: ./classifier
    environment:
      TZ: CET
      KAFKA_BROKER_URL: broker:9092
    volumes: 
      - ./logs:/logs:rw
    networks:
      - storage

  influxdb:
    container_name: influxdb
    build: ./influxdb
    environment:
      TZ: CET
    ports:
      - 8086:8086
    networks:
      - storage

  telegraf:
    container_name: telegraf
    build: ./telegraf
    environment:
      TZ: CET
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - storage
    depends_on:
      - influxdb

  # analytics:
  #   container_name: analytics
  #   build: ./analytics
  #   environment:
  #     TZ: CET
  #   ports:
  #     - 5005:5005
  #     - 3000:3000
  #     - 3001:3001
  #   networks:
  #     - storage
  #   depends_on:
  #     - collector
  #     - classifier


networks:
  storage:
    driver: bridge
  api:
    driver: bridge
