version: '3'

services:

  generator:
    container_name: generator
    build: ./generator
    environment:
      TZ: CET
      LINES_PER_SECOND: 0.5
    volumes: 
      - ./logs:/logs:rw

  collector:
    container_name: classifier
    build: ./collector
    environment:
      TZ: CET
      KAFKA_BROKER_URL: broker:9092
    volumes: 
      - ./logs:/logs:rw

  classifier:
    container_name: classifier
    build: ./classifier
    environment:
      TZ: CET
      KAFKA_BROKER_URL: broker:9092
    volumes: 
      - ./logs:/logs:rw

  influxdb:
    container_name: influxdb
    build: ./influxdb
    environment:
      TZ: CET
    ports:
      - 8086:8086

  nginx:
    restart: always
    image: "nginx:latest"
    ports:
      - "80:80"
      - "443":"443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - appseed-app

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge          
networks:
  default:
    external:
      name: kafka-network
